# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
         
    ],
    datas=[
        ('about.ui', '.'),
        ('chats.ui', '.'),
        ('extras.ui', '.'),
        ('how.ui', '.'),
        ('main.ui', '.'),
        ('reminder.ui', '.'),
        ('ripple_button.ui', '.'),
        ('settings.ui', '.'),
        ('audio/reminder_notification.wav', 'audio'),
        ('icons/chatbot.png', 'icons'),
        ('icons/chatbot_icon.ico', 'icons'),
        ('icons/microphone.png', 'icons'),
        ('icons/send.png', 'icons'),

        ('about_ui.py', '.'), 
        ('chats.py', '.'), 
        ('chats_ui.py', '.'), 
        ('extras.py', '.'), 
        ('extras_ui.py', '.'), 
        ('floating_chat.py', '.'), 
        ('how_ui.py', '.'), 
        ('main_ui.py', '.'), 
        ('main.py' ,'.'),
        ('mic_icon_popup.py', '.'), 
        ('music_animation.py', '.'), 
        ('reminder.py', '.'), 
        ('reminder_ui.py', '.'), 
        ('ripple_buttin_ui.py', '.'), 
        ('settings.py', '.'), 
        ('settings_ui.py', '.'), 
        ('setup.py', '.'), 
        ('test.py', '.'), 
        ('voice.py', '.'), 
        ('__init__.py', '.'),

        ('animations/loading_animation.py', 'animations'),
        ('functionalities/chat_json_data.py', 'functionalities'),
        ('functionalities/get_audio_input_device.py', 'functionalities'),
        ('functionalities/get_summary.py', 'functionalities'),
        ('functionalities/rw_json_data.py', 'functionalities'),
        ('functionalities/set_audio_input_device.py', 'functionalities'),
        ('functionalities/__init__.py', 'functionalities'),
        ('functionalities/extract_information/get_reminder_info.py', 'functionalities/extract_information'),
        ('functionalities/features/check_similarity.py', 'functionalities/features'),
        ('functionalities/features/get_application_name.py', 'functionalities/features'),
        ('functionalities/features/reminder_singleton.py', 'functionalities/features'),
        ('functionalities/features/__init__.py', 'functionalities/features'),
        ('functionalities/manager/data_manager.py', 'functionalities/manager'),
        ('functionalities/reminder/gloabal_scheduler.py', 'functionalities/reminder'),
        ('functionalities/reminder/reminder_window.py', 'functionalities/reminder'),
        ('functionalities/reminder/schedule_reminder.py', 'functionalities/reminder'),
        ('functionalities/reminder/trigger_reminder.py', 'functionalities/reminder'),
        ('functionalities/reminder/__init__.py', 'functionalities/reminder'),
        ('functionalities/features/open_close_app.py' ,'functionalities/features'),
        ('functionalities/features/change_volume.py' ,'functionalities/features'),
        ('functionalities/features/play_music.py' ,'functionalities/features'),
        ('functionalities/features/power_options.py' ,'functionalities/features'),



        
    ],
    hiddenimports=['uuid' ,'w2n' ,'AppOpener','comtypes.stream' ,'dateparser' ,'word2number'  ,'pyaudio','sounddevice','schedule','bs4','psutil','pyttsx3','requests','spacy','SpeechRecognition','word2number','PyQt5.QtMultimedia','pyqtspinner','dateutil','dateutil.parser','beautifulsoup4','regex','speech_recognition'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Nikki Assistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon = 'icons/chatbot_icon.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
