# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reminder.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(595, 192)
        Form.setStyleSheet("background-color:rgb(225, 223, 216);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("background-color:#CDB4DB;\n"
"border-radius:14px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton.setStyleSheet("background-color:rgba(255,255,255 ,0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/chatbot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.Reminder = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Reminder.setFont(font)
        self.Reminder.setStyleSheet("")
        self.Reminder.setObjectName("Reminder")
        self.horizontalLayout.addWidget(self.Reminder)
        self.verticalLayout.addWidget(self.widget_2)
        self.reminder_text = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.reminder_text.setFont(font)
        self.reminder_text.setStyleSheet("background-color:#CDB4DB;\n"
"border-radius:14px;\n"
"font-size:13pt")
        self.reminder_text.setLineWidth(1)
        self.reminder_text.setObjectName("reminder_text")
        self.verticalLayout.addWidget(self.reminder_text)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Reminder.setText(_translate("Form", "Reminder"))
        self.reminder_text.setPlaceholderText(_translate("Form", "Hello this is your reminder!!"))
